### ISSUE TITLE
I want to add a Reinforcement learning example to this list.

### ISSUE THREAD

**Issue by AYUSHBlaze** [amrzv/awesome-colab-notebooks#1]
The example is from tensorflow's documentation.

**Comment by amrzv** [comment]
Hi. It would be great if you can write 
| name | description | link |
|------|-------------|:------------:|

after that I can add it to the table.

**Comment by AYUSHBlaze** [comment]
**Name-**Playing CartPole with the Actor-Critic Method
**Description-**This tutorial demonstrates how to implement the Actor-Critic method using TensorFlow to train an agent on the Open AI Gym CartPole-V0 environment. The reader is assumed to have some familiarity with policy gradient methods of reinforcement learning.
**Link-**https://www.tensorflow.org/tutorials/reinforcement_learning/actor_critic

**Comment by amrzv** [comment]
Thanks, I will update the table later.
